name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  pedometer: ^4.0.0
  health: ^13.2.1
  permission_handler: ^11.0.0
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^5.1.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

